### PR TITLE
bug-fix: add a check for unlimited dimension in read_variables 

### LINKED ISSUE #402: bug: read_variables not checking if unlimited dimension exists for each file
:bug: 🦏 

### Describe the bug

1. List the steps someone needs to take to reproduce the bug.  
run fill_inflation_restart with wrf 
run filter with inflation read from file, e.g.
```
   inf_flavor                  = 2,                      0,  
   inf_initial_from_restart    = .true.,                .false.,
   inf_sd_initial_from_restart = .true.,                .false.,
```

2. What was the expected outcome?
filter reads the inflation file sucessfully

3. What actually happened?  
filter errors out when reading the inflation files

read_state is expecting the inflation files to match the template file, but dart created files do not.

See https://github.com/NCAR/DART/issues/359#issuecomment-1187818595 for notes on unlimited dimension in dart created files. 

### Error Message  
Please provide any error messages.

```
 ERROR FROM:
  source : netcdf_utilities_mod.f90
  routine: read_variables: nf90_inquiredimension
  message: unlimitedDim length: NetCDF: Invalid dimension ID or name
  message: ...
 
MPT ERROR: Rank 124(g:124) is aborting with error code 99.
        Process ID: 19440, Host: r14i3n25, Program: /glade/work/XXXXX/DART_WRF/models/wrf/work_base/rundir/filter
        MPT Version: HPE MPT 2.25  08/14/21 03:05:20
```

### Which model(s) are you working with?
wrf

### Version of DART      
Which version of DART are you using? 
v10.5.1
I believe this bug came in with v10.2.0

### Have you modified the DART code?   
No  

### Build information
Please describe:  
 1. Cheyenne
 2. intel

### PR DESCRIPTION
**Pull request by hkershaw-brown**
## Description:

DART created netcdf files vs. model created files do not necessarily have the same netcdf dimensions. 

For DART created files only 'time' gets created as unlimited.  The model netcdf files, e.g. WRF, may have an unlimited dimension 'Time' that is converted limited dimension when DART creates a file from scratch. So if you create an inflation file from scratch with DART `fill_inflation_restart`, it may not match the model template file.

This pull request adds a check to see if the unlimited dimension exists and adjust accordingly before reading netcdf variables.
The bug was introduced in pull request https://github.com/NCAR/DART/pull/374 v10.1.0 for TIEGCM.
The write_variables has the check, but the read_variables was overlooked. 

See https://github.com/NCAR/DART/issues/359#issuecomment-1187818595 for notes on unlimited dimension in dart created files. 

moved the slice_start(:)=1 outside the if statement since both branches set the same value

### Fixes issue
Fixes #402

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Documentation changes needed?

- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.

### Tests

Tested using the wrf tutorial  with a smaller number of obs:
`/glade/scratch/hkershaw/DART/Bugs/bug_wrf_netcdf_read/test_dir/rundir`
fill_inflation_restart (create fill from scratch)
fill_inflation_restart (fill in an existing wrfinput file)
run filter with these inflation files (unlimited and limited dimension)

## Checklist for merging

- [x] Updated changelog entry
- [ ] Documentation updated
- [x] Update conf.py

## Checklist for release
- [ ] Merge into main
- [ ] Create release from the main branch with appropriate tag
- [ ] Delete feature-branch

## Testing Datasets

- [ ] Dataset needed for testing available upon request
- [x] Dataset download instructions included
- [ ] No dataset needed

### CODE REVIEW

File: assimilation_code/modules/io/direct_netcdf_mod.f90 [hunk 1]
```diff
@@ -856,22 +856,28 @@ subroutine read_variables(ncfile_in, var_block, start_var, end_var, domain)
    allocate(counts(num_dims))
    allocate(slice_start(num_dims))
 
+   slice_start(:) = 1 ! default to read all dimensions start at 1
+
    if (has_unlimited_dim(domain)) then
 
-      slice_start(:) = 1 ! default to read all dimensions start at 1
       counts(num_dims) = 1 ! one slice of unlimited dimesion
```
Comment (mjs2369) [inline assimilation_code/modules/io/direct_netcdf_mod.f90:863]: The variable counts may need to be assigned differently for netcdf files with unlimited dimensions versus without. More specifically, the length of the counts array will probably need to be different depending on whether or not there is an unlimited dimension. If there are no unlimited dimensions, the length should be 3. If there is an unlimited dimension (time), then the length should be 4 to include x, y, z, and time.

**Review by mjs2369 — CHANGES_REQUESTED** [review]
Not sure why my original comment didn't reference the correct lines, but lines 863, 864, and 881 may need some changes to correct the variable count.

File: assimilation_code/modules/io/direct_netcdf_mod.f90 (hunk 1 above)
Comment (hkershaw-brown) [reply assimilation_code/modules/io/direct_netcdf_mod.f90:863]: check this out:
I've being trying to break this by making counts and slice_start massive

```fortran
 854    ! number of dimensions and length the variable
 855    num_dims = get_io_num_dims(domain, i)
 856    allocate(counts(num_dims+200))
 857    allocate(slice_start(num_dims+200))
```

Here is the count docs.
https://docs.unidata.ucar.edu/netcdf-fortran/current/f90-variables.html#f90-writing-data-values-nf90_put_var
Screen Shot 2022-10-06 at 3 54 04 PM

I think if count is too long, but the extra element is 1, that is ok because that is what netcdf is doing anyway:
The netcdf code does stuff like this: (netcdf-fortran-4.5.3/fortran/netcdf_expanded.f90).  

```fortran
1145    function nf90_put_var_1D_EightByteReal(ncid, varid, values, start, count, stride, map)
1146      integer,                         intent( in) :: ncid, varid
1147      real (kind = EightByteReal), dimension(:), &
1148                                       intent( in) :: values
1149      integer, dimension(:), optional, intent( in) :: start, count, stride, map
1150      integer                                      :: nf90_put_var_1D_EightByteReal
1151 
1152      integer, dimension(nf90_max_var_dims) :: localStart, localCount, localStride, localMap
1153      integer                               :: numDims, counter
1154 
1155      ! Set local arguments to default values
1156      numDims                 = size(shape(values))
1157      localStart (:         ) = 1
1158      localCount (:numDims  ) = shape(values)
1159      localCount (numDims+1:) = 1
1160      localStride(:         ) = 1
1161      localMap   (:numDims  ) = (/ 1, (product(localCount(:counter)), counter = 1, numDims - 1) /)
1162 
1163      if(present(start))  localStart (:size(start) )  = start(:)
1164      if(present(count))  localCount (:size(count) )  = count(:)
1165      if(present(stride)) localStride(:size(stride)) = stride(:)
1166      if(present(map))  then
1167        localMap   (:size(map))    = map(:)
1168        nf90_put_var_1D_EightByteReal = &
1169           nf_put_varm_double(ncid, varid, localStart, localCount, localStride, localMap, values)
1170      else if(present(stride)) then
1171        nf90_put_var_1D_EightByteReal = &
1172           nf_put_vars_double(ncid, varid, localStart, localCount, localStride, values)
1173      else
1174        nf90_put_var_1D_EightByteReal = &
1175           nf_put_vara_double(ncid, varid, localStart, localCount, values)
1176      end if
1177    end function nf90_put_var_1D_EightByteReal

```

I'm not totally convinced yet, but figured I would share this update of why it 'works' as is.

Comment (mjs2369) [reply assimilation_code/modules/io/direct_netcdf_mod.f90:863]: The only thing I'm a little confused about is the last element of counts. What is the purpose of the extra element, why does it have a default value of 1, and what does that default value of 1 tell NetCDF to do? Similarly, in what cases will values other than 1 be used in the last element, and will this still work if count is too long and the last variable is not 1?

What is a record variable, and why/how does this affect the last element of counts? The documentation says that if the variable is a record variable, then the last element corresponds to the number of records to write, but I'm not really sure what this means. We can talk about all this more at the drop in today too.

**Review by mjs2369 — APPROVED** [review]

**Comment by hkershaw-brown** [comment]
bundle with Marlee's imminent bug fix for #390

File: assimilation_code/modules/io/direct_netcdf_mod.f90 (hunk 1 above)
Comment (hkershaw-brown) [reply assimilation_code/modules/io/direct_netcdf_mod.f90:863]: chatted about this in person today.

**Comment by hkershaw-brown** [comment]
To test before this gets merged:

- [ ] fill_inflation_restart (filter  - wrf created file)
- [ ] fill_inflation_restart (filter - dart created file)
- [ ] lorenz_96 model_mod_check (perfect_input.nc)
- [ ] lorenz_96 filter (time & member dimension filter_input.nc)
- [ ] TIEGCM (last time slice)
