### PR TITLE
MOM6: correct u grid for get_interp_handle, correct distance when there are land points in get_close_state

### LINKED ISSUE #929: bug: MOM6 dist is set for whole array when dry land
:bug: Your bug may already be reported!
Please search on the [issue tracker](https://github.com/NCAR/DART/issues) before creating a new issue.

### Describe the bug

1. List the steps someone needs to take to reproduce the bug.  
    call get_close_state 
2. What was the expected outcome?
    distance for close states that are dry land should get large dist, ocean state should get actual distance
3. What actually happened?  
     dist array is being set rather than dist(ii) so all close state are 'far away' if there are land points. 
 

### Error Message  
No error just incorrect

### Which model(s) are you working with?
MOM6

### Version of DART      
Which version of DART are you using? 
You can find the version using `git describe --tags`  
v11.12.0

### Have you modified the DART code?   
No  

### Build information
Please describe:  
 1. Derecho
 2. intel

### LINKED ISSUE #930: bug: MOM6 incorrect assignment of quad interpolation
:bug: 

### Describe the bug
The routine `get_interp_handle` that selects the interpolation handle for the different ocean variables does not use the U grid. The if statement doesn't check for U grid. In its current form, the temperature interpolation handle is used for U. This impacts the `model_interpolate` code  where the variable `interp` is [assigned](https://github.com/NCAR/DART/blob/4e1529649f126af77d2a9435271eb6b067842f09/models/MOM6/model_mod.f90#L261).

### Error Message  
No error messages. Technically, I haven't run MOM6 but seems incorrect 

### Which model(s) are you working with?
I'm working with ROMS but using MOM6 and other ocean interfaces for ideas

### Version of DART      
v9.11.4-2644-gc0d334676

### Have you modified the DART code?   
No

### LINKED ISSUE #933: bug: MOM6 model_mod four quad corners not correct.
🐳 

### Describe the bug

MOM6 model_mod uses four_ilons, four_ilats for its quads. 
However

 four_ilons(1), four_ilats(1)
 four_ilons(1), four_ilats(2)
 four_ilons(2), four_ilats(1)
 four_ilons(2), four_ilats(2)

should be

 four_ilons(1), four_ilats(1)
 four_ilons(2), four_ilats(2)
 four_ilons(3), four_ilats(3)
 four_ilons(4), four_ilats(4)

routines:
model interpolate
  layer loop to find thickness
  state_on_quad
on_land_quad
on_basin_edge

### Error Message  
No error, just incorrect results

### Which model(s) are you working with?
MOM6

### Version of DART      
v11.12.0, but been in since v10.7.0

### Have you modified the DART code?   
No

### Build information
Please describe:  
 1. any machine
 2. any compiler
 

Thanks to Moha for the report.

### LINKED ISSUE #934: bug: MOM6 sensible temperature conversion
:bug: Your bug may already be reported!
Please search on the [issue tracker](https://github.com/NCAR/DART/issues) before creating a new issue.

This calculation should be using the location of the obs. 
lon_lat_vert(3) rather than depth_at_x

https://github.com/NCAR/DART/blob/ba604a564e5950d74b78c6b057da13ec5ebc01ee/models/MOM6/model_mod.f90#L381-L383

Also Moha raised a concern that the units are not correct for pressure, 

See also the notes on [salinity units](https://github.com/NCAR/DART/issues/773#issuecomment-2549050039)
Here is the original issue #773 
Here is the pull request #782 
I am not sure what the correct units/equation are. It would be good to confirm was is correct and document the functions in the code. 

### Version of DART      
Which version of DART are you using? 
You can find the version using `git describe --tags`  
v11.12.0

### Have you modified the DART code?   
No

### Build information
Please describe:  
 1. Any machine
 2. Any compiler

### PR DESCRIPTION
**Pull request by hkershaw-brown**
## Description:

Bug fixes for MOM6 
Fix: correct u grid for get_interp_handle
Fix: large dist set only for dry land state indices

simplifies the wet/dry for a single point. 

### Fixes issue

Fixes #930 
Fixes #929
Fixes #933
Fixes #934 

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Documentation changes needed?

- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.

### Tests
Please describe any tests you ran to verify your changes.

## Checklist for merging

- [ ] Updated changelog entry
- [ ] Documentation updated
- [ ] Update conf.py

## Checklist for release
- [ ] Merge into main
- [ ] Create release from the main branch with appropriate tag
- [ ] Delete feature-branch

## Testing Datasets

- [ ] Dataset needed for testing available upon request
- [ ] Dataset download instructions included
- [ ] No dataset needed

### CODE REVIEW

**Comment by hkershaw-brown** [comment]
converted to draft, since adding the fix for #933, #934

File: models/MOM6/model_mod.f90 [hunk 1]
```diff
@@ -308,21 +308,11 @@ subroutine model_interpolate(state_handle, ens_size, location, qty_in, expected_
...
-      th_indx = get_dart_vector_index(four_ilons(2), four_ilats(1), i, dom_id, thick_id)
-      quad_vals(3, :) = get_state(th_indx, state_handle)
-      
-      ! corner4
-      th_indx = get_dart_vector_index(four_ilons(2), four_ilats(2), i, dom_id, thick_id)
-      quad_vals(4, :) = get_state(th_indx, state_handle)
+      do corner = 1, 4
+         th_indx = get_dart_vector_index(four_ilons(corner), four_ilats(corner), i, dom_id, thick_id)
+          quad_vals(corner, :) = get_state(th_indx, state_handle)
+      enddo
```
Comment (mgharamti) [inline models/MOM6/model_mod.f90:314]: This is a lot cleaner than the previous version.

**Review by mgharamti — COMMENTED** [review]
The changes now make use of all 4 corners of the quad for interpolation. Please see my other comment on the conversion, but other than that this is looking much better.

**Comment by hkershaw-brown** [comment]
> The changes now make use of all 4 corners of the quad for interpolation. Please see my other comment on the conversion, but other than that this is looking much better.

Thanks for looking at this Moha, super helpful.

File: models/MOM6/model_mod.f90 [hunk 2]
```diff
@@ -368,9 +368,9 @@ subroutine model_interpolate(state_handle, ens_size, location, qty_in, expected_
          return
       endif
 
-      pressure_dbars =  0.059808_r8*(exp(-0.025_r8*lon_lat_vert(3)) - 1.0_r8)  &
+      pressure_bars =  0.059808_r8*(exp(-0.025_r8*lon_lat_vert(3)) - 1.0_r8)  &
                         + 0.100766_r8*lon_lat_vert(3) + 2.28405e-7_r8*lon_lat_vert(3)**2
-      expected_obs = sensible_temp(expected_pot_temp, expected_salinity, pressure_dbars)
+      expected_obs = sensible_temp(expected_pot_temp, expected_salinity, pressure_bars*10.0_r8)
```
Comment (mgharamti) [inline models/MOM6/model_mod.f90:373]: Excellent!

**Comment by hkershaw-brown** [comment]
I'm going to pop this back on draft, because with the regional mom6 NWA case ( xh = 740 ; yh = 780 ;)  I am getting "large interp residual"  96 times.  So I want to dig into what is going on with that before releasing this fix

**Comment by hkershaw-brown** [comment]
checked the values for one of the quads giving "large interp residual", for thickness:
Screenshot 2025-07-25 at 8 33 24 PM

does give large residuals, when you give these to quad_bilinear_interp see notebook:
https://github.com/hkershaw-brown/DART-probe/blob/mom6/plot_quads.ipynb
