### PR TITLE
Distribution fixes

### LINKED ISSUE #717: bug: beta distribution not correct (failing tests)
:bug: Your bug may already be reported!
Please search on the [issue tracker](https://github.com/NCAR/DART/issues) before creating a new issue.

### Describe the bug

1. Run https://github.com/NCAR/DART/tree/stats-tests/developer_tests/beta_dist
2. What was the expected outcome? test passes
3. What actually happened?  test fails: max difference in inversion is    7.8846335608728112E-006
 max difference should be less than 1e-14

### Error Message  

[hkershaw:work] (stats-tests) > ./test_beta_dist 

```
 --------------------------------------
 Starting ... at YYYY MM DD HH MM SS = 
                 2024  8 13 15 13  6
 --------------------------------------

  set_nml_output Echo NML values to log file only
 Absolute value of differences should be less than 1e-15
           1  -2.2204460492503131E-016   3.0531133177191805E-016
           2  -6.9388939039072284E-018  -3.0357660829594124E-018
           3   0.0000000000000000        0.0000000000000000     
           4   0.0000000000000000       -1.1102230246251565E-016
           5   8.3266726846886741E-017   0.0000000000000000     
           6   0.0000000000000000       -1.1102230246251565E-016
           7  -1.1102230246251565E-016  -2.2204460492503131E-016
  inv_cdf  Failed to converge for quantile    0.0000000000000000
 ----------------------------
 max difference in inversion is    7.8846335608728112E-006
 max difference should be less than 1e-14

 --------------------------------------
 Finished ... at YYYY MM DD HH MM SS = 
                 2024  8 13 15 13  6
 --------------------------------------
```

### Which model(s) are you working with?
none

### Version of DART      
Which version of DART are you using? 
v11.6.0-4-g2feb86983

### Have you modified the DART code?   
Yes, added test harnesses
https://github.com/NCAR/DART/tree/stats-tests

### Build information
Please describe:  
 1. Mac M2
 2. GNU Fortran (MacPorts gcc13 13.2.0_4+stdlib_flag) 13.2.0

### LINKED ISSUE #786: Gamma_distribution_mod
moved from #717 so this doesn't get buried.  

Gamma_distribution_mod also changed in https://github.com/NCAR/DART/commit/5b3850fb1a08fff0ebce3f95283fef29de431bdc to only support supports the standard gamma
distribution that is bounded below by 0 and unbounded above. 

Q. what does this mean for user options (bounds) set in[ QCEFF table](https://docs.google.com/spreadsheets/d/1CRGHWc7boQt81pw2pDxEFY6WPyQeCh64OwPyoVMqijE/edit?gid=0#gid=0)? Ignored for Gamma and Beta?

_Originally posted by @hkershaw-brown in https://github.com/NCAR/DART/issues/717#issuecomment-2562999527_

### LINKED ISSUE #787: distribution param type partially unset for normal distribution.
☠️ skeleton

### PR DESCRIPTION
**Pull request by hkershaw-brown**
## Description:

Fixes for distributions that have been hanging out on https://github.com/NCAR/DART/tree/beta_distribution_fix

* beta distribution only supporting standard beta (previously had some generalization that was only partially done causing tests to fail #717)
* gamma distribution only supporting standard gamma (previously had some generalization only partially done)
* normal distribution, setting all distribution_params_type values (not causing known problems, but maybe future problems)

Forcing the gamma and beta qceff options (bounds) in qceff table to be:
 * GAMMA_DISTRIBUTION (lower bound at 0)
 * BETA_DISTRIBUTION (bound between 0 and 1)

test in developer_tests/qceff/test_force_bounds

I can split this into 3 pull requests if that is easier to review. 

Screenshot 2024-12-26 at 3 41 28 PM

### Fixes issue

fixes #717  only supporting standard beta
fixes #786 only supporting standard gamma - note see issue, still have upper and lower bound
fixes #787 see notes - initialize distribution_param_type to UNSET?

There was an E_MSG about failing to converge, switched this to E_ALLMSG since the failure could be on any task. 

I think the documentation for the qceff available distributions probably needs updating to clarify that the GAMMA & BETA bounds are fixed (QCEFF table values are ignored) Edit: went ahead and changed the documentation. 

https://github.com/NCAR/DART/blob/bddda57a7df96b4b956db33cec5238b9850fc825/guide/qceff_probit.rst?plain=1#L126-L135

Maybe this is sufficient, I dunno:

```
 * GAMMA_DISTRIBUTION (lower bound at 0)
 * BETA_DISTRIBUTION (bound between 0 and 1)
```

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Documentation changes needed?

- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly.

### Tests
Please describe any tests you ran to verify your changes.
developer_tests/*_dist
developer_tests/qceff/test_force_bounds

## Checklist for merging

- [ ] Updated changelog entry
- [ ] Documentation updated
- [ ] Update conf.py

## Checklist for release
- [ ] Merge into main
- [ ] Create release from the main branch with appropriate tag
- [ ] Delete feature-branch

## Testing Datasets

- [ ] Dataset needed for testing available upon request
- [ ] Dataset download instructions included
- [ ] No dataset needed

### CODE REVIEW

File: assimilation_code/modules/assimilation/normal_distribution_mod.f90 [hunk 1]
```diff
@@ -285,14 +287,17 @@ function inv_std_normal_cdf(quantile) result(x)
...
 real(r8) :: mean, sd
 
 ! Set the mean and sd to 0 and 1 for standard normal
 mean        = 0.0_r8;     sd          = 1.0_r8
 p%params(1) = mean;       p%params(2) = sd
 
+! Normal is unbounded
+p%bounded_below = .false.;       p%bounded_above = .false.
+p%lower_bound   = missing_r8;    p%upper_bound   = missing_r8
+
```
Comment (hkershaw-brown) [inline assimilation_code/modules/assimilation/normal_distribution_mod.f90:300]: not setting the distribution type here:

`p%distribution_type = NORMAL_DISTRIBUTION`

File: assimilation_code/modules/assimilation/normal_distribution_mod.f90 [hunk 2]
```diff
@@ -157,6 +158,9 @@ function inv_weighted_normal_cdf(alpha, mean, sd, q) result(x)
 real(r8) :: normalized_q
 
 ! VARIABLES THROUGHOUT NEED TO SWITCH TO DIGITS_12
+! The comment above is not consistent with the performance of these routines 
+! as validated by test_normal. There is no evidence that this is still
+! required.
```
Comment (hkershaw-brown) [inline assimilation_code/modules/assimilation/normal_distribution_mod.f90:163]: I am not following this comment. 
"'digits12' is reserved for real variables that MUST retain 64 bits of precision", when dart is built with r8=r4

Are you running test_normal with r8=r4?  Should the distribution tests all be run with r8=r4

https://github.com/NCAR/DART/blob/bddda57a7df96b4b956db33cec5238b9850fc825/assimilation_code/modules/utilities/types_mod.f90#L80-L98

Comment (hkershaw-brown) [reply assimilation_code/modules/assimilation/normal_distribution_mod.f90:163]:
```
[hkershaw:work](distribution-fixes) > ./test_normal_dist

 --------------------------------------
 Starting ... at YYYY MM DD HH MM SS = 
                 2025  1  6 10 43 42
 --------------------------------------

  set_nml_output Echo NML values to log file only
 Absolute value of differences should be less than 1e-15
 Matlab Comparison Tests: PASS    0.00000000    
 FAIL: Max inversion diff    17.0500488      > bound    1.00000001E-10 for quantiles <   0.899999976    
 FAIL: Max inversion diff    17.0500488      > bound    1.00000001E-10 for quantiles <   0.990000010    
 FAIL: Max inversion diff    17.0500488      > bound    1.00000001E-10 for quantiles <   0.999000013    
 FAIL: Max inversion diff    17.0500488      > bound    1.00000001E-10 for quantiles <   0.999899983    
 FAIL: Max inversion diff    17.0500488      > bound    1.00000001E-10 for quantiles <   0.999989986    
 FAIL: Max inversion diff    17.0500488      > bound    9.99999972E-10 for quantiles <   0.999998987    
 FAIL: Max inversion diff    17.0500488      > bound    9.99999994E-09 for quantiles <   0.999999881    
 FAIL: Max inversion diff    17.0500488      > bound    1.00000001E-07 for quantiles <    1.00000000    
 FAIL: Max inversion diff    17.0500488      > bound    1.00000001E-07 for quantiles <    1.00000000    
 FAIL: Max inversion diff    17.0500488      > bound    9.99999997E-07 for quantiles <    1.00000000    
 FAIL: Max inversion diff    17.0500488      > bound    9.99999975E-06 for quantiles <    1.00000000    
 FAIL: Max inversion diff    17.0500488      > bound    9.99999975E-05 for quantiles <    1.00000000    
 FAIL: Max inversion diff    17.0500488      > bound    1.00000005E-03 for quantiles <    1.00000000    
 FAIL: Max inversion diff    17.0500488      > bound    9.99999978E-03 for quantiles <    1.00000000    
 FAIL: Max inversion diff    17.0500488      > bound   0.100000001     for quantiles <    1.00000000    
 FAIL: Max inversion diff    17.0500488      > bound    1.00000000     for quantiles <    1.00000000    

 --------------------------------------
 Finished ... at YYYY MM DD HH MM SS = 
                 2025  1  6 10 43 43
 --------------------------------------
```

```diff
[hkershaw:work](distribution-fixes) > git diff          
diff --git a/assimilation_code/modules/utilities/types_mod.f90 b/assimilation_code/modules/utilities/types_mod.f90
index 8e4b376ee..ecf791cf7 100644
--- a/assimilation_code/modules/utilities/types_mod.f90
+++ b/assimilation_code/modules/utilities/types_mod.f90
@@ -81,8 +81,8 @@ integer, parameter :: i8 = SELECTED_INT_KIND(13)
 ! TO RUN WITH REDUCED PRECISION REALS (and use correspondingly less memory)
 ! comment OUT the r8 definition below and use the second one:
 integer, parameter :: r4 = SELECTED_REAL_KIND(6,30)
-integer, parameter :: r8 = SELECTED_REAL_KIND(12)   ! 8 byte reals
-!integer, parameter :: r8 = r4                      ! alias r8 to r4
+!integer, parameter :: r8 = SELECTED_REAL_KIND(12)   ! 8 byte reals
+integer, parameter :: r8 = r4                      ! alias r8 to r4
 ```

File: assimilation_code/modules/assimilation/probit_transform_mod.f90 [hunk 3]
```diff
@@ -141,8 +141,7 @@ subroutine transform_to_probit(ens_size, state_ens_in, distribution_type, p, &
    call to_probit_gamma(ens_size, state_ens, p, probit_ens, use_input_p, &
       bounded_below, bounded_above, lower_bound, upper_bound)
```
Comment (hkershaw-brown) [inline assimilation_code/modules/assimilation/probit_transform_mod.f90:142]: Similar to `to_probit_beta` change below, since bounds are fixed [0,unbounded)
```suggestion
   call to_probit_gamma(ens_size, state_ens, p, probit_ens, use_input_p)
```

File: assimilation_code/modules/assimilation/probit_transform_mod.f90 [hunk 4]
```diff
@@ -279,8 +278,7 @@ subroutine to_probit_gamma(ens_size, state_ens, p, probit_ens, use_input_p, &
       call error_handler(E_ERR, 'to_probit_gamma', errstring, source)
    endif
```
Comment (hkershaw-brown) [inline assimilation_code/modules/assimilation/probit_transform_mod.f90:279]: Not general anymore. Remove this?

File: assimilation_code/modules/assimilation/probit_transform_mod.f90 (hunk 3 above)
Comment (hkershaw-brown) [reply assimilation_code/modules/assimilation/probit_transform_mod.f90:142]: also subroutine to_probit_gamma(ens_size, state_ens, p, probit_ens, use_input_p)

File: assimilation_code/modules/assimilation/normal_distribution_mod.f90 (hunk 1 above)
Comment (hkershaw-brown) [reply assimilation_code/modules/assimilation/normal_distribution_mod.f90]: set in 7930bff444afa473dc22838fc6029c71dc7b666e

File: assimilation_code/modules/assimilation/probit_transform_mod.f90 (hunk 3 above)
Comment (hkershaw-brown) [reply assimilation_code/modules/assimilation/probit_transform_mod.f90]: fixed in bcbeefe23043c149dd6eb6f906194f9bc1a61f69

File: assimilation_code/modules/assimilation/probit_transform_mod.f90 (hunk 4 above)
Comment (hkershaw-brown) [reply assimilation_code/modules/assimilation/probit_transform_mod.f90]: fixed in bcbeefe23043c149dd6eb6f906194f9bc1a61f69

**Comment by hkershaw-brown** [comment]
@mjs2369 can you take a look at this when you get a chance.

**Review by mjs2369 — COMMENTED** [review]
Looking good Helen. My only questions/comments are posted

File: developer_tests/qceff/work/runall.sh [hunk 5]
```diff
@@ -41,6 +41,9 @@ else
 fi
 }
 
+cp input.nml input.nml.bak
+cp input.nml.no_alg input.nml
```
[the remark this answers is not in the document]
Comment (hkershaw-brown) [reply developer_tests/qceff/work/runall.sh:45]: the other tests switch in an &algorithm_info_nml with various qceff_tables by appending &algorithm_info_nml to the end of the input.nml
The namelist read in fortran will take the first occurrence of the namelist in the file and ignore any subsequent ones. So the input.nml.no_alg is to start with a input.nml that doesn't have a &algorithm_info_nml in it. 
This reason it is in this pull request is test_force_bounds needs an input.nml, so now have input.nml and input.nml.no_alg

File: assimilation_code/modules/assimilation/normal_distribution_mod.f90 (hunk 2 above)
Comment (hkershaw-brown) [reply assimilation_code/modules/assimilation/normal_distribution_mod.f90]: no resolution on this, so just put a comment on the comment about the comment. [8583817](https://github.com/NCAR/DART/pull/788/commits/85838171d351910d600fdddb5c66195dcedcd733)

**Review by mjs2369 — APPROVED** [review]
Good stuff @hkershaw-brown
