### PR TITLE
Bug fix - Fixes issue if FillValue is NaN

### LINKED ISSUE #323: bug: Checking equality of _FillValues that are NaNs in io_filenames_mod causes DART to exit.
:bug:  :bug:  :bug: 

### Describe the bug

Checking equality of _FillValues that are NaNs in io_filenames_mod causes DART to exit.

`check_attribute_value` is called to check `_FillValue` and `missing_value` with the following code (r4 and r8) versions:

```
if ( nf90_get_att(ncFile, ncVarID, att_string, ret_spvalR4) == NF90_NOERR ) then
   if (spvalR4 /= ret_spvalR4) then
      write(msgstring,*) ' variable attribute, ', trim(att_string), ' in state', spvalR4, &
                         ' does not match ', trim(att_string), ' ', ret_spvalR4, ' in ', trim(filename)
      call error_handler(E_ERR, 'check_attribute_value_r4', msgstring, source)
   endif
endif
```

If _FillValue is NaN then `(spvalR4 /= ret_spvalR4)` is always true. 

### Error Message  

```
 ERROR FROM:

  source : io_filenames_mod.f90
  routine: check_attribute_value_r4
  message:   variable attribute, _FillValue in state            NaN  does not match _FillValue             NaN  in /glade/work/gharamti/wrfhydro_dart/florence/initial_ens/hybrid/init_ens/member_000/HYDRO_RST.2018-08-01_00:00_DOMAIN1
```

### Which model(s) are you working with?
Found with wrf-hydro, will effect any netcdf variable that has a missing or fill value attribute that is NaN.

### Version of DART      
9.12 (been there since at least 2016 though)

### Have you modified the DART code?   
No

Note to myself:  You can test for NaNs before testing /=, but why do we even have to check the missing/fill value attribute is the same? State vs. netcdf file. Input vs. Output.   Query the missing/fill value before you write?

### PR DESCRIPTION
**Pull request by Benjamin-Gunn**
Fixes #323

## Description:

Bug fix for the Nan FillValue.

### Fixes issue
Fixes #323 

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Documentation changes needed?

- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.

### Tests
Tested with wrf NaN case.

## Checklist for merging

- [ ] Updated changelog entry
- [ ] Documentation updated
- [ ] Version tag 

## Testing Datasets

- [x] Dataset needed for testing available upon request
- [ ] Dataset download instructions included
- [ ] No dataset needed

### CODE REVIEW

File: assimilation_code/modules/io/io_filenames_mod.f90 [hunk 1]
```diff
@@ -717,6 +717,9 @@ subroutine check_attribute_value_r4(ncFile, filename, ncVarID, att_string, spval
 real(r4) :: ret_spvalR4
 
 if ( nf90_get_att(ncFile, ncVarID, att_string, ret_spvalR4) == NF90_NOERR ) then
+   if (isnan(ret_spvalR4)) then
```
Comment (hkershaw-brown) [inline assimilation_code/modules/io/io_filenames_mod.f90:720]:
```suggestion
   if (ret_spvalR4 /= ret_spvalR4) then 
```

File: assimilation_code/modules/io/io_filenames_mod.f90 [hunk 2]
```diff
@@ -742,6 +745,9 @@ subroutine check_attribute_value_r8(ncFile, filename, ncVarID, att_string, spval
 real(r8) :: ret_spvalR8
 
 if ( nf90_get_att(ncFile, ncVarID, att_string, ret_spvalR8) == NF90_NOERR ) then
+   if (isnan(ret_spvalR8)) then
```
Comment (hkershaw-brown) [inline assimilation_code/modules/io/io_filenames_mod.f90:748]:
```suggestion
   if (ret_spvalR8 /= ret_spvalR8) then
```

**Review by hkershaw-brown — CHANGES_REQUESTED** [review]
Great fix, thanks Benjamin.

I've been testing the fix on Cheyenne with several different compilers.  (ifort, gfortran, nvfortran). One of the compilers (nvfortran) that people use on Cheyenne does _not_ have an `isnan` function. 

So let's replace `isnan` with `ret_spvalR8 /= ret_spvalR8` to make the code work with all the Cheyenne compilers. 

If you are interested, we have has some discussion of NaNs here #176 
Once you have access to Cheyenne you will be able to try out the various compilers. 

Cheers,
Helen

**Review by hkershaw-brown — APPROVED** [review]
