### PR TITLE
Remove loops over calendar types where not needed

### LINKED ISSUE #653: loops over calendar types are unneeded
### Describe the bug
The time_manager subroutines set_calendar_type_string and get_calendar_string
give the right answers, but the loops over the calendar types (0,...,max_type) are unneeded
and can be confusing.
1. List the steps someone needs to take to reproduce the bug.  
To see the bug, put print statements in the loops that show the loop index and the input and output variables.
Build and run a program that handles calendars; filter, model_mod_check, ...
3. What was the expected outcome?
When a loop finds the answer it needs, it should exit.  Or it should do a different test during each iteration.
5. What actually happened?  
In set_calendar_type_string the loop exits after the 0th iteration if it matches a calendar,
or it tries to match the same cstring 6 more times before exiting.
In get_calendar_string there's a similar loop over calendar types, where the outcome is known after the 0th iteration, 
but it goes  on to do the same test 6 more times.

### Error Message  
See your messages from  the suggestion above here.

### Which model(s) are you working with?
 model_mod_check

### Screenshots   
```
  get_calendar_string  : calendar_type =            3
  set_calendar_string  : in types loop i, mystring =            0 GREGORIAN    [the correct string is found on the 0th)
  set_calendar_string  : in types loop i, mystring =            1 GREGORIAN    [ 6 more iterations find the same]
  set_calendar_string  : in types loop i, mystring =            2 GREGORIAN
  set_calendar_string  : in types loop i, mystring =            3 GREGORIAN
  set_calendar_string  : in types loop i, mystring =            4 GREGORIAN
  set_calendar_string  : in types loop i, mystring =            5 GREGORIAN
  set_calendar_string  : in types loop i, mystring =            6 GREGORIAN

```
### Version of DART      
v9.12.refactored-1264-g38f4139ba

### Have you modified the DART code?   
Only to print messages.  I committed those to branch calendar_loops.

### Build information
Please describe:  
 1. The machine you are running on 
 Mac laptop, but this happens on any machine.  
 3. The compiler you are using (e.g. gnu, intel).  
gfortran, but this will happen with any compiler (unless it recognizes a spurious loop)

The intention may have been to have an array of calendar_types(0:max_type), 
then use variable calendar_type to access an element of it without the explicit if-blocks,
but somehow that was not implemented, or was partially removed.
Removal of the loops would be a simple fix.  Implementation of the calendar_types array
would be more involved, but would probably result in smaller  or more elegent code.
That might be an opportunity to make NO_CALENDAR = 0 and let actual calendars have 1,...,max_type

### PR DESCRIPTION
**Pull request by mjs2369**
## Description:

The subroutines set_calendar_type_string and get_calendar_string in the time_manager_mod have unnecessary loops over the number of max_types (calendar types). This PR removes these loops for improved code efficiency and readability

### Fixes issue
fixes #653 

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Documentation changes needed?

- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.

### Tests
Ran model_mod_check and filter with print statements to ensure the correct calendar_type was being set/used

## Checklist for merging

- [ ] Updated changelog entry
- [ ] Documentation updated
- [ ] Update conf.py

## Checklist for release
- [ ] Merge into main
- [ ] Create release from the main branch with appropriate tag
- [ ] Delete feature-branch

## Testing Datasets

- [ ] Dataset needed for testing available upon request
- [ ] Dataset download instructions included
- [x] No dataset needed

### CODE REVIEW

**Comment by hkershaw-brown** [comment]
For commits like these, where you've just missed something from the commit (removing the loop variable) and there aren't a bunch of people working with the pull request, you can rebase and squash the commits together. 
I'll go ahead an squish them.

File: assimilation_code/modules/utilities/time_manager_mod.f90 [hunk 1]
```diff
@@ -714,47 +713,34 @@ subroutine set_calendar_type_string(calstring)
...
-   elseif ( cstring == 'GREGORIAN' ) then
-           calendar_type  = GREGORIAN
-           found_calendar = .true.
-           exit WhichCalendar
-   endif
-
-enddo WhichCalendar
+if     ( cstring == 'NO_CALENDAR' ) then
+        calendar_type  = NO_CALENDAR
+        found_calendar = .true.
```
Comment (hkershaw-brown) [inline assimilation_code/modules/utilities/time_manager_mod.f90:718]: You don't need the `found_calendar = .true.` then a check on found_calendar. 

```
if     ( cstring == 'NO_CALENDAR' ) then
        calendar_type  = NO_CALENDAR
elseif ( cstring == 'NO CALENDAR' ) then   ! allow this as a synonym 
        calendar_type  = NO_CALENDAR
...
else
   write(errstring,*)'Unknown calendar ',calstring
   call error_handler(E_ERR,'set_calendar_type_string',errstring,source)
endif
```

**Review by hkershaw-brown — CHANGES_REQUESTED** [review]

**Review by hkershaw-brown — APPROVED** [review]
Looks good Marlee!

For reference I added (and tested with) a unit test in the DART-tests repo:
https://github.com/NCAR/DART-tests/tree/main/unit/time_manager_mod
