### PR TITLE
Check list of state variables for required ones

### LINKED ISSUE #662: cam-se fails if CLDICE, CLDLIQ, or Q (or PS) is not in the state vector
### Describe the bug

1. List the steps someone needs to take to reproduce the bug. 
   Build a cam-se filter.
   Set model_nml:state_variables to a set of variables that is "missing" one or more of the moisture variables.
   Assimilate any appropriate observation (#343 may provide files that are helpful for setting up an assimilation).
3. What was the expected outcome?
    The existence of state_variables in the namelist implies that the user is free to define the model state, 
    so the expected outcome is that the observations will be assimilated.
5. What actually happened?  
    All observations fail in the forward operator (QC=4).
    
### Error Message  
There is not enough diagnostic messaging from model_mod to learn the cause of the failure.
Adding messages about the various istatus contents leads to the discovery that build_dry_mass_pressure_columns requests values for QTY_SPECIFIC_HUMIDITY, QTY_CLOUD_LIQUID_WATER,
and QTY_CLOUD_ICE.  If one of those fails, the failure code is immediately returned to the calling routine
without any diagnostic message.  The calling routine converts the code to a generic failure code,
which eventually is converted into QC=4, which is not very informative, given the large number of ways
that the forward operator can fail.

### Which model(s) are you working with?
cam-se 
A similar issue applies to cam-fv too, because PS is required (in both).  
No one has ever excluded PS and reported a problem.

### Version of DART      
Which version of DART are you using? 
Any version after the refactoring which uses cam-common-code and after build_dry_mass_pressure_columns
was added.  (I don't see it mentioned in the git log output, so I don't know when it was installed.)
The version I modified and sent to Nuo Chen for testing is v9.12.refactored-1915-gb3e00330f.
If a cleaner version number is needed, I'll work on finding one.

### Have you modified the DART code?   
I added diagnostic prints, but did not change any calculations or procedure calls.
There are several possible solutions to this problem:

1. Tell users in documentation that state_variables must include those 3 moisture variables.  This is minimal effort, but unreliable.
2. Add code to check for the presence of the moisture variables and fail if one is missing.
3. Add printed messages (controlled by debug_level) that list useful debugging information: subroutine, istatus, related variables,...  This can save hours to days of debugging.  If this is part of the chosen solution, I can provide a version that does some of this.
4. Define (hardcode) a minimal set of state variables which are always in the state and allow users to add variables through the namelist.

A question related to 1. is whether those 3 variables are all that are required to correctly calculate the dry mass pressures.

### Build information
Please describe:  
 1. The machine you are running on:  any machine
 2. The compiler you are using: any compiler

### PR DESCRIPTION
**Pull request by kdraeder**
## Description:

Users can specify in model_nml which variables should be in the state vector.
They are currently free to leave out variables that are required for some calculations.
Filter writes no useful message about this problem when it fails, which results in a long debugging process.
This fix adds a function call after model_nml has been read and parsed to check whether required variables are in the state, and exit with a helpful message when one is missing.  
The lists of required variables are different for cam-fv and cam-se, and may change in the future.

### Fixes issue
fixes #662

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Documentation changes needed?

- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.

### Tests
I ran both cam-fv and cam-se using model_nml:state_variables which contained

1. all required variables
2. all except for PS
3. all except for CLDICE (cam-se only; dry mass calculation)

These were not set up using the usual setup_ scripts.  They use the "assimilation-only" test set up 
which is (partly?) in /glade/derecho/scratch/raeder/Test_cam-se_dry_mass.

## Checklist for merging

- [ ] Updated changelog entry
- [ ] Documentation updated
- [ ] Update conf.py

## Checklist for release
- [ ] Merge into main
- [ ] Create release from the main branch with appropriate tag
- [ ] Delete feature-branch

## Testing Datasets

- [ ] Dataset needed for testing available upon request
- [ ] Dataset download instructions included
- [ ] No dataset needed

### CODE REVIEW

File: models/cam-se/model_mod.f90 [hunk 1]
```diff
@@ -593,6 +600,11 @@ subroutine model_interpolate(state_handle, ens_size, location, obs_qty, interp_v
 !SENote Do further study of how we want to return istatus for various failures
 ! For now return istatus 12 for any of the failure modes
 if (any(istatus /= 0)) then
+   ! Debug vert info
+   if(debug_level > 12) then
+      write(string1,*)'get_se_quad_vals failed istatus(:) = ', istatus
+      call error_handler(E_MSG,routine,string1,source,revision,revdate)
+   endif
```
Comment (hkershaw-brown) [inline models/cam-se/model_mod.f90:607]: whats the goal of adding this message? And does it need to be in this pull request?
E_MSG means only task 0 will print this. If other tasks have a non-zero istatus you won't get a message.

File: models/cam-se/model_mod.f90 [hunk 2]
```diff
@@ -1271,6 +1283,12 @@ subroutine get_se_quad_vals(state_handle, ens_size, varid, obs_qty, corners, &
                                 four_vert_fracts(icorner, :), my_status)
 
       if (any(my_status /= 0)) then
+         ! Debug se_values
+         if(debug_level > 12) then
+            write(string1,*)'find_se_vertical_levels failed vert, corner,  my_status(:) = ', &
+                             lon_lat_vert(3), corners(icorner),my_status
+            call error_handler(E_MSG,routine,string1,source,revision,revdate)
+         endif
```
Comment (hkershaw-brown) [inline models/cam-se/model_mod.f90:1291]: same message comment: do you need to have task 0 print this?

File: models/cam-se/model_mod.f90 [hunk 3]
```diff
@@ -1295,7 +1313,14 @@ subroutine get_se_quad_vals(state_handle, ens_size, varid, obs_qty, corners, &
...
    !SENote Technically nothing happens after this point anyway? So is this statement needed.
-   if (any(my_status /= 0)) return
+   if (any(my_status /= 0)) then
+      if(debug_level > 12) then
+         write(string1,*)'get_se_four_(non)state_values failed varid, my_status(:) = ', &
+                          varid, my_status
+         call error_handler(E_MSG,routine,string1,source,revision,revdate)
+      endif
+      return
+   endif
```
Comment (hkershaw-brown) [inline models/cam-se/model_mod.f90:1323]: same message comment: do you need to have task 0 print this?

File: models/cam-se/model_mod.f90 [hunk 4]
```diff
@@ -1305,7 +1330,15 @@ subroutine get_se_quad_vals(state_handle, ens_size, varid, obs_qty, corners, &
...
-         if (any(my_status /= 0)) return
+         if (any(my_status /= 0)) then
+            ! Debug se_values
+            if(debug_level > 12) then
+               write(string1,*)'get_se_values_from_varid failed varid, corner,  my_status(:) = ', &
+                                varid, corners(icorner),my_status
+               call error_handler(E_MSG,routine,string1,source,revision,revdate)
+            endif
+            return
+         endif
```
Comment (hkershaw-brown) [inline models/cam-se/model_mod.f90:1341]: same message comment: do you need to have task 0 print this?
You could set a conditional debug in a debugger to catch these on any task if you need to debug.

File: models/cam-se/model_mod.f90 [hunk 5]
```diff
@@ -1747,7 +1780,8 @@ subroutine build_dry_mass_pressure_columns(ens_handle, ens_size, nlevels, column
       half_pressure(k + 1) = half_pressure(k) + &
          !gravity * (a_width(k)*dry_mass_top + b_width(k)*dry_mass_sfc(n)) * sum_dry_mix_ratio(k, n)
          ! SENote: NEXT LINE IS BELIEVED TO BE CORRECT BUT NEEDS TO BE VETTED WITH CGD
-         gravity * (a_width(k)*dry_mass_top / grid_data%hyai%vals(1) + b_width(k)*dry_mass_sfc(n)) * sum_dry_mix_ratio(k, n)
+         gravity * (a_width(k)*dry_mass_top/grid_data%hyai%vals(1) + b_width(k)*dry_mass_sfc(n)) &
+                 * sum_dry_mix_ratio(k, n)
```
Comment (hkershaw-brown) [inline models/cam-se/model_mod.f90:1784]: Is this a change to the calculation? Or are you just wrapping the line.
If it is just a line wrap change, I would not do this change in this pull request.

File: models/cam-se/model_mod.f90 [hunk 6]
```diff
@@ -1386,8 +1419,8 @@ end subroutine get_se_four_state_values
 !-----------------------------------------------------------------------
 !>
 
-! Returns my_status 0 for success, 16 if unable to find values at lower level
-! and 17 if unable to find values at upper level.
+! Returns my_status 0 for success, 26 if unable to find values at lower level
+! and 27 if unable to find values at upper level.
```
Comment (hkershaw-brown) [inline models/cam-se/model_mod.f90:1423]: What is the significance of 26 vs 16? 27 vs 17? Did these clash with other my_status values?

File: models/cam-se/model_mod.f90 [hunk 7]
```diff
@@ -1,3 +1,6 @@
+! "Debug pressure calc" shows changes which prevent users from asking for total(moist) pressure
+! without providing the moisture variables in the state vector.
+
```
Comment (hkershaw-brown) [inline models/cam-se/model_mod.f90:3]: What is this comment referring to?  
It looks like some notes from the previous commit. I'd remove this or if it is a necessary comment, put the comment by the code it is describing.

File: models/cam-se/model_mod.f90 [hunk 8]
```diff
@@ -3319,6 +3353,43 @@ end subroutine solve_quadratic
...
+subroutine verify_state_var_list
+
+! No return is needed.  A diagnostic statement is printed before a potential failure
+! of get_varid_from_varname.  Success means carry on.
+
+! There could be more moisture variables than the traditional 3.
+character(len=32), dimension(10) :: var_names
+integer:: i, varid
+
+data var_names /'PS', 'Q', 'CLDLIQ', 'CLDICE', 6*''/
```
Comment (hkershaw-brown) [inline models/cam-se/model_mod.f90:3365]: functionally this looks to be doing what is should, but it seems a little over complicated. 

Why do you have 10 var_names, but only 4 names, and 6 blank strings?

Why is PS in the var_names array? 
You could check for PS (always required), then loop though your sometimes required variables. 
That way 
```
i = 1
i = i+1
if (dry_mass_vertical_coordinate .and. precise_dry_mass_get_close) then
do while (var_names(i) .ne. '')
  i = i + 1
enddo
endif
```
becomes
```
check for PS
if (dry_mass_vertical_coordinate .and. precise_dry_mass_get_close) then
  do i = 1, 3
  enddo
endif
```

File: models/cam-se/model_mod.nml [hunk 9]
```diff
@@ -30,6 +30,13 @@
    homme_map_file                  = 'SEMapping.nc'
    cs_grid_file                    = 'SEMapping_cs_grid.nc'
    vertical_localization_coord     = 'PRESSURE'
+   state_variables  = 'T',     'QTY_TEMPERATURE',         'NA', 'NA', 'UPDATE'
+                      'U',    'QTY_U_WIND_COMPONENT',    'NA', 'NA', 'UPDATE'
+                      'V',    'QTY_V_WIND_COMPONENT',    'NA', 'NA', 'UPDATE'
+                      'Q',     'QTY_SPECIFIC_HUMIDITY',   'NA', 'NA', 'UPDATE'
+                      'CLDLIQ','QTY_CLOUD_LIQUID_WATER',  'NA', 'NA', 'UPDATE'
+                      'CLDICE','QTY_CLOUD_ICE',           'NA', 'NA', 'UPDATE'
+                      'PS',    'QTY_SURFACE_PRESSURE',    'NA', 'NA', 'UPDATE'
```
Comment (hkershaw-brown) [inline models/cam-se/model_mod.nml:39]: good catch putting these in model_mod.nml

File: models/cam-se/model_mod.f90 [hunk 10]
```diff
@@ -345,6 +349,9 @@ subroutine static_init_model()
 ! to set up what will be read into the cam state vector
 call set_cam_variable_info(cam_template_filename, state_variables)
 
+! Verify that required variables are in the state vector.
+call verify_state_var_list
```
Comment (hkershaw-brown) [inline models/cam-se/model_mod.f90:353]: this is a nitpick, but I think your routine name is clear enough that you don't need this comment.

```
! this routine does stuff
call do_stuff
```

File: models/cam-fv/model_mod.f90 [hunk 11]
```diff
@@ -2380,6 +2383,30 @@ subroutine get_close_state(gc, base_loc, base_type, locs, loc_qtys, loc_indx, &
...
+subroutine verify_state_var_list
+
+! No return is needed.  A diagnostic statement is printed before a potential failure
+! of get_varid_from_varname.  Success means carry on.
+
+! There could be more moisture variables than the traditional 3.
+character(len=32), dimension(10) :: var_names
+integer:: i, varid
+
+data var_names /'PS', 9*''/
```
Comment (hkershaw-brown) [inline models/cam-fv/model_mod.f90:2397]: I don't think you need a data statement & and i variable here
You only have 'PS' so you could call 

`varid = get_varid_from_varname(domain_id, 'PS')`

**Review by hkershaw-brown — CHANGES_REQUESTED** [review]
Hi Kevin,

Functionally the code looks to be doing the checks for the required state variables. At the moment you code seems a bit over complicated, I've put some comments on simplifying it. 

You have some debugging statements, that will only print on task 0. I'd advocated for not putting these debugging statements in (see comment on the ~3 places these debug statements were added)

The change in value for the istatus (16 vs 26) - it would be good to know what this change was for.

Do you have a cam-se case I can grab on Derecho that I can add to our test cases? If not I can spin one up. 

Cheers,
Helen

**Comment by hkershaw-brown** [comment]
Hi Kevin, just checking in on this cam-se pull request and the review comments. Is your plan to work on this?

**Comment by kdraeder** [comment]
I do plan to finish this after reviewing 740 for Jeff.
I lost momentum on it during the AGU scramble.
Thanks for all of your comments!

File: models/cam-se/model_mod.f90 (hunk 4 above)
Comment (kdraeder) [reply models/cam-se/model_mod.f90:1341]: Thanks for the debugger suggestion.  Now I understand why people prefer to remove most debugging code; it's apparently easy to install temporarily when using debuggers.  I use debuggers so seldom that I need to climb a big learning curve every time, so I end up opting for adding debugging code directly.  So it looks like these should be removed, even though they would have saved me time.

**Comment by kdraeder** [comment]
The change of istatus values from {16,17} to {26,27} in get_se_four_nonstate_values was useful to me because {16,17} are already used in get_se_four_state_values, so I couldn't see which subroutine was returning a non-0 value.  It doesn't seem to break anything or add code, so I left it in to save time in the future.

File: models/cam-se/model_mod.f90 (hunk 5 above)
Comment (kdraeder) [reply models/cam-se/model_mod.f90:1784]: No calculation change - just a reformatting so that I could see the calculation more clearly.
It seems easy to see that, so I didn't comment about it in the commit message.  Should I have?
Or is this a question of sticking strictly to the topic of the PR?
Do we ever do PRs that are focused on making the code more readable, fixing typos,...?

File: models/cam-se/model_mod.f90 (hunk 7 above)
Comment (kdraeder) [reply models/cam-se/model_mod.f90:3]: This was just useful during the debugging and fixing process.  I've removed it.

File: models/cam-se/model_mod.f90 (hunk 8 above)
Comment (kdraeder) [reply models/cam-se/model_mod.f90:3365]: My intent was to write generic and flexible code; more fields may need to be added to var_names in the future and it would be nice if the only required change is to var_names, and not finding where var_names is dimensioned and then used, and changing the sizes there.  Although size(var_names) coud be used for the loop.
A more comprehensive fix in the future might involve var_names being passed in, so the code I wrote would be more easily adapted to that.
But if the priority is short code to solve the immediate problem, then I'll do that.

File: models/cam-fv/model_mod.f90 (hunk 11 above)
Comment (kdraeder) [reply models/cam-fv/model_mod.f90:2397]: I was making it consistent with the cam-se version to make comparisons easier, and to keep the flexibility for adding fields to the list in the future.
If that's misguided I'll simplify the cam-fv version.

File: models/cam-se/model_mod.f90 (hunk 5 above)
Comment (hkershaw-brown) [reply models/cam-se/model_mod.f90:1784]: It is  this a question of sticking strictly to the topic of the PR.  We have very limited test coverage, hand-run tests, and limited reviewers.

**Comment by hkershaw-brown** [comment]
Hi Kevin, are you planning on working on this this week, if not I'll go ahead and make the changes unless you have a burning desire to do the changes yourself.

**Comment by hkershaw-brown** [comment]
> Hi Kevin, are you planning on working on this this week, if not I'll go ahead and make the changes unless you have a burning desire to do the changes yourself.

Hi just pinging again on this, is this something that you are working on?, if not I'll go ahead and make the changes. Cheers,
Helen

**Comment by kdraeder** [comment]
@hkershaw-brown  I've made the 'resolved' changes in my clone.  
There are a couple open questions above about which additional changes I should make, 
so when we've answered  these questions I'll make the remaining recommended changes 
and push the commit.

**Comment by hkershaw-brown** [comment]
> @hkershaw-brown I've made the 'resolved' changes in my clone.

Go ahead and commit and push the changes for the 'resolved', otherwise it is not resolved in the repo. You can put other changes in another commit.

File: models/cam-fv/model_mod.f90 (hunk 11 above)
Comment (hkershaw-brown) [reply models/cam-fv/model_mod.f90:2397]: yup simplify the cam-fv version

File: models/cam-se/model_mod.f90 (hunk 8 above)
Comment (kdraeder) [reply models/cam-se/model_mod.f90:3333]: @hkershaw-brown  do you want any changes here, or is my motivation convincing?

**Comment by hkershaw-brown** [comment]
Oh simplify for sure!

File: models/cam-se/model_mod.f90 (hunk 8 above)
Comment (hkershaw-brown) [reply models/cam-se/model_mod.f90:3333]: Oh simplify for sure!

**Review by hkershaw-brown — APPROVED** [review]
Nice! thanks Kevin 
Approved!
